// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-HsqFaRA6So6T4XILn4S_g24b71oyr7o',
    appId: '1:289627400479:web:f37294f6be0b81ed16a82a',
    databaseURL: "https://digilocal-go-digital-in-minute-default-rtdb.firebaseio.com/",  // remove this line
    messagingSenderId: '289627400479',
    projectId: 'digilocal-go-digital-in-minute',
    authDomain: 'digilocal-go-digital-in-minute.firebaseapp.com',
    storageBucket: 'digilocal-go-digital-in-minute.firebasestorage.app',
    measurementId: 'G-P9YMC0T1G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzyPSH2NPZtRydQANZYAsDyYNCsHMEpMA',
    appId: '1:289627400479:android:0e56eba2ae52683e16a82a',
    databaseURL: "https://digilocal-go-digital-in-minute-default-rtdb.firebaseio.com/",  // remove this line
    messagingSenderId: '289627400479',
    projectId: 'digilocal-go-digital-in-minute',
    storageBucket: 'digilocal-go-digital-in-minute.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEZGICELBgxDpGWl0Um7ZDcFLwoio7HzU',
    appId: '1:289627400479:ios:a2b5999b00d8691f16a82a',
    databaseURL: "https://digilocal-go-digital-in-minute-default-rtdb.firebaseio.com/",  // remove this line
    messagingSenderId: '289627400479',
    projectId: 'digilocal-go-digital-in-minute',
    storageBucket: 'digilocal-go-digital-in-minute.firebasestorage.app',
    iosBundleId: 'com.example.digilocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEZGICELBgxDpGWl0Um7ZDcFLwoio7HzU',
    appId: '1:289627400479:ios:a2b5999b00d8691f16a82a',
    messagingSenderId: '289627400479',
    projectId: 'digilocal-go-digital-in-minute',
    storageBucket: 'digilocal-go-digital-in-minute.firebasestorage.app',
    iosBundleId: 'com.example.digilocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-HsqFaRA6So6T4XILn4S_g24b71oyr7o',
    appId: '1:289627400479:web:c6bd359fe99f440116a82a',
    databaseURL: "https://digilocal-go-digital-in-minute-default-rtdb.firebaseio.com/",  // remove this line
    messagingSenderId: '289627400479',
    projectId: 'digilocal-go-digital-in-minute',
    authDomain: 'digilocal-go-digital-in-minute.firebaseapp.com',
    storageBucket: 'digilocal-go-digital-in-minute.firebasestorage.app',
    measurementId: 'G-ZCRSYVQ5QF',
  );
}
